<?php

namespace App\Console\Commands;

use App\Models\BoardMember;
use App\Models\Team;
use Illuminate\Console\Command;

class LoadTeam extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'import:team';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Import Team members';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return int
     */
    public function handle()
    {
        $teams = $this->getTeam();

        foreach($teams as $key => $team){
            $t = Team::whereName($key)->first();
            foreach($team as $person){
                $member = new BoardMember;
                $member->name = $person['name'];
                $member->title = $person['title'];
                $member->image = $person['image'];
                $member->bio = $person['bio'];

                $t->boardmembers()->save($member);
            }
        }

        return 0;
    }


    private function getTeam()
    {
        return json_decode('{"Board of Directors": [{"name": "Donald W. Parry", "title": "Board Co-Chair", "image": "https://wp.wilfordwoodruffpapers.org/wp-content/uploads/2020/05/Donald-W-Parrys-image-1.jpg", "bio": "Don is a professor of the Hebrew Bible and the Dead Sea Scrolls at Brigham Young University; he holds the Abraham O. Smoot Professorship. He has been a member of the International Team of Translators of the Dead Sea Scrolls since 1994; he is also a member of the Dead Sea Scrolls Foundation Board of Directors. He has authored or edited forty books and written more than eighty articles. His professional memberships and affiliations include International Organization for the Study of the Old Testament, Society of Biblical Literature, Foundation for the Dead Sea Scrolls, National Association for Professors of Hebrew, and American Academy of Religion. He co-founded the Wilford Woodruff Papers Foundation in 2019 with Jennifer Mackley. He believes the Wilford Woodruff Papers are vital to our understanding of the formative years of The Church of Jesus Christ of Latter-day Saints as well as to the present-day Church."},
		{"name": "Jordan Woodruff Clements", "title": "Board Co-Chair", "image": "https://wp.wilfordwoodruffpapers.org/wp-content/uploads/2020/05/Jordan-W-Clements-image.jpg", "bio": "Jordan obtained a bachelor\'s degree in English from Brigham Young University and graduated magna cum laude from the J. Reuben Clark Law School. Jordan is a co-founder of Rock Creek Capital, a private investment firm. He was the founder and chairman of Children First Utah, a scholarship foundation that provided thousands of scholarships to low income children to attend schools of their parents\' choosing. He and his wife Julie presided over the Minnesota Minneapolis Mission from 2011-2014 and serve together on the Board of the International Center for Law and Religion Studies. He also serves as the vice chair of the Freedoms Foundation at Valley Forge. His interest in the Wilford Woodruff Papers Foundation stems from the “Woodruff” in his name, Wilford being his great-great grandfather and Abraham Owen Woodruff being his great grandfather. Because his life has been blessed tremendously by their faith and example, he would like to pay tribute to his ancestors, in some small way, and provide enhanced access to the history of the Church as recorded by Wilford Woodruff."},
		{"name": "Jennifer Ann Mackley", "title": "Executive Director", "image": "https://wp.wilfordwoodruffpapers.org/wp-content/uploads/2020/05/Jennifer-Mackleys-Headshot.jpg", "bio": "Jennifer has been an attorney for 24 years and is currently in private practice. She has authored or edited 21 books including Wilford Woodruff\'s Witness: The Development of Temple Doctrine (2014). She has made numerous presentations and podcasts based on her research of Wilford Woodruff\'s life and his pivotal role in the restoration of temple worship in the nineteenth century. She was asked to serve as the Historian for the Wilford Woodruff Family Association in 2014 and co-founded the Wilford Woodruff Papers Foundation in 2019 with Donald Parry. Her hope in transcribing and publishing Wilford Woodruff\'s Papers is to help Church members and historians alike understand the importance of the temple and gain insights into the Restoration through Wilford\'s unique perspective of the revelatory process."},
		{"name": "Joan E. Boren", "title": "Board Relations", "image": "https://wp.wilfordwoodruffpapers.org/wp-content/uploads/2020/08/Joan-e1597238320470.png", "bio": "Joan has a master\'s degree in Biology from The University of Illinois at Chicago. She is the director of the Obsidian Foundation, Inc, has served on the Board of Trustees for the Boise School district, the Boise Philharmonic and currently serves on the board of the Ayaan Hirsi Ali Foundation. Joan has served as an instructor in the Institute program of The Church of Jesus Christ of Latter-day Saints and worked for many years in a public affairs role for the church. She has come to appreciate Wilford Woodruff as a prophet whose writings are very applicable to our time because of his focus on temples, the Restoration, and personal revelation. Joan believes that knowledge of his experiences and perspective will become increasingly more valuable to members of the Church."},
		{"name": "Gary L. Crittenden", "title": "Chair, Audit & Finance Committee", "image": "https://wp.wilfordwoodruffpapers.org/wp-content/uploads/2021/01/Gary-Crittenden-pic.png", "bio": "Gary is currently an Executive Director of HGGC, and was previously Chairman, CEO, and a Managing Director of HGGC. Gary spent the first 12 years of his career at Bain & Company and then served as CFO of Monsanto, Sears Roebuck and Company, Melville Corporation, Filene\'s Basement, the American Express Company, and most recently Citigroup. On three separate occasions, the readers of Institutional Investor Magazine named Gary one of the \'Best CFOs in America.\' From 2017 to 2020, Gary served as the Managing Director of the Missionary Department of the Church of Jesus Christ of Latter-day Saints. Gary has a BS degree from Brigham Young University and an MBA from Harvard Business School."},
		{"name": "Jane Clayton Johnson", "title": "Public Relations", "image": "https://wp.wilfordwoodruffpapers.org/wp-content/uploads/2020/05/Jane-Johnson-image.jpg", "bio": "Jane graduated from Brigham Young University with a degree in Elementary Education. She then spent over two decades studying the art of education and found her passion in both learning and teaching various subjects in numerous settings. She and her family have spent significant time abroad, particularly in Taiwan and China where she studied and became fluent in Mandarin Chinese. As alumni of the BYU Jerusalem program, she and her husband have dedicated years of time and research to Ancient Near Eastern and Biblical studies, which they share a fondness for, along with their six children. Jane believes the detailed and expansive records of Wilford Woodruff will add color, depth, and breadth to the story of the Restoration, and she is particularly eager to help move the work of the Wilford Woodruff Papers Foundation forward as a means to bless the youth of the coming generation."},
		{"name": "Jason R. Kotter", "title": "", "image": "https://wp.wilfordwoodruffpapers.org/wp-content/uploads/2020/05/Jason-Kotter-image.jpg", "bio": "Jason attended Boise State University after serving a full-time mission for The Church of Jesus Christ of Latter-Day Saints in Canada. Having worked in the real estate industry most of his life, Jason co-founded Athlos Academies in 2006. Athlos focuses on providing schools with solutions centered around developing the whole child. In 2018 Jason initiated the idea of building a life-sized replica of the Tabernacle of Moses in Meridian Idaho as a catalyst for teaching the youth in his Stake about the temple. The Tabernacle has since been erected at various locations and reached thousands of individuals. He firmly believes that the Wilford Woodruff Papers will bring further clarity and understanding to the Gospel of Jesus Christ and enhance our appreciation of temple worship."},
		{"name": "Matthew T. Kotter", "title": "Chair – Development Committee", "image": "https://wp.wilfordwoodruffpapers.org/wp-content/uploads/2020/05/Matthwe-Kotters-headshot.jpg", "bio": "Matt graduated from Brigham Young University with a BS in Accounting and received a Master of Public Administration degree from the University of North Texas. Matt is the President of Braintree Properties, a commercial real estate firm. His interest in and appreciation for Church history has been lifelong. Matt frequently gives firesides for both youth and adults that focus on the land of Israel, the Abrahamic Covenant and the Gathering of Israel. He is excited to support the Wilford Woodruff Papers project and the insights that it will no doubt give regarding the Plan of Salvation."},
		{"name": "J. Gregory Lake", "title": "Treasurer", "image": "https://wp.wilfordwoodruffpapers.org/wp-content/uploads/2020/05/Gregory-Lake-image-1.jpg", "bio": "Greg graduated from Brigham Young University with a BA in Economics after serving a full-time mission for The Church of Jesus Christ of Latter-Day Saints in Sweden. He then received his Juris Doctorate from the University of Arizona and has been in the private practice of law since 1987. He is currently working, with others, on a glossary of nineteenth century legal terms for the Joseph Smith Papers. Greg committed to leadership of the Wilford Woodruff Papers Foundation in order to continue to bring light to the Restoration."},
		{"name": "Diane LeFrandt Nelson", "title": "", "image": "https://wp.wilfordwoodruffpapers.org/wp-content/uploads/2021/02/Diane-Lefrandt-Nelson.jpg", "bio": "Diane is a public relations and digital marketing thought leader who has advised clients across the globe. She established her own public relations and marketing agency, Diane Lefrandt Digital, after working as the senior consultant at Coltrin & Associates. Diane received her Bachelor\'s degree in Public Relations from Brigham Young University. She first read Wilford Woodruff\'s biography when she was 16 and gained great respect for him. She is thrilled to be working on this project in order to help bring to life his records."},
		{"name": "Kristy Wheelwright Taylor", "title": "", "image": "https://wp.wilfordwoodruffpapers.org/wp-content/uploads/2020/05/Kristy-Taylors-headshot-1.jpg", "bio": "Kristy has a master\'s degree in Humanities from Brigham Young University and has since been an English Instructor at Purdue University, a copy editor, technical writer, caterer, travel writer, and historical researcher and writer. She is now a volunteer coordinator and a writer for various websites and publications. Her most recent project was a series of twelve articles on the life of Queen Elizabeth II for a digital and print magazine. Kristy is eager to learn more about Church History and to make Wilford Woodruff valuable documents available to a wider audience of readers and learners."}
	],
	"Staff": [
		{"name": "Steven C. Harper", "title": "Executive Editor", "image": "https://wp.wilfordwoodruffpapers.org/wp-content/uploads/2020/05/Steven-C-Harpers-image-731x1024-1.jpg", "bio": "Steve is a professor of Church history and doctrine at Brigham Young University. After graduating from BYU with a BA in history, he earned an MA in American history from Utah State University, and a PhD in early American history from Lehigh University. He began teaching at BYU Hawaii in 2000, then joined the faculty at BYU in 2002, and taught at the BYU Jerusalem Center in 2011–2012. He became a volume editor of The Joseph Smith Papers and the document editor for BYU Studies in 2002. In 2012 Steve was appointed as the managing historian and a general editor of Saints: The Story of the Church of Jesus Christ in the Latter Days, and was named editor in chief of BYU Studies Quarterly in 2018. He has authored numerous books and dozens of articles including: Promised Land (2006), Making Sense of the Doctrine and Covenants (2008), Joseph Smith\'s First Vision (2012), and First Vision: Memory and Mormon Origins (2019)."},
		{"name": "Sherilyn Farnes", "title": "Managing Editor", "image": "https://wp.wilfordwoodruffpapers.org/wp-content/uploads/2020/08/Sherilyn.jpg", "bio": "Sherilyn earned her BA and MA from Brigham Young University before returning to school in 2015 to earn her PhD in history from Texas Christian University, where she is currently a PhD candidate. She has worked with The Joseph Smith Papers Project, the Edward Partridge Papers, and on the writing team of Saints, a four-volume history of The Church of Jesus Christ of Latter-day Saints. She has been interviewed for history programs about early Latter-day Saint history such as America\'s Sacred Ground: Kirtland. Her current research analyzes the interactions of Native Americans, Latter-day Saints, French fur traders, missionaries, and other settlers in the western Missouri borderlands during the Jacksonian Era."},
		{"name": "Lorin E. Groesbeck", "title": "Editorial Assistant", "image": "https://wp.wilfordwoodruffpapers.org/wp-content/uploads/2020/08/Lorin-Groesbeck-1536x1024.jpg", "bio": "Lorin graduated from Brigham Young University with a bachelor\'s degree in American Studies and minors in music and digital humanities. While at BYU, she served as the editor of Americana and worked as an assistant researching women\'s religious history. For the past two years Lorin has been an editorial assistant for the Joseph Smith Papers project where her primary responsibility was to prepare content for the project\'s website. She is excited for the opportunity to help make Woodruff\'s archive more accessible to scholars and Church members alike."},
		{"name": "Brent C. Hall", "title": "Director of Philanthropy", "image": "https://wp.wilfordwoodruffpapers.org/wp-content/uploads/2020/08/Brent-e1597238804998.jpg", "bio": "Most recently he was the Associate Director of Major Gifts and Donor Liaison for LDS Philanthropies from 2006-2018. Brent graduated from BYU in International Relations. He was a director and Board Member of the Foundation for Ancient Research and Mormon Studies (FARMS) for many years and spent the last twelve years in the Philanthropy Department of the Church of Jesus Christ of Latter-day Saints. As the Associate Director of Major Gifts and Donor Liaison he helped in many major fundraising campaigns for educational, humanitarian, and other priorities around the world. Wilford Woodruff\'s example of dedication, focus, humility, testimony, and contributions to the Restoration made Brent excited to be a part of this project."},
		{"name": "Brenda L. Homer", "title": "Biographies Manager", "image": "https://wp.wilfordwoodruffpapers.org/wp-content/uploads/2020/08/Brenda-e1597237591657.jpg", "bio": "Brenda is currently the missionary co-chair of the Biographical Team at the Church History Library. Her primary responsibility is to research and edit for the Church Historian\'s Press project, The Diaries of Emmeline B. Wells and for The Joseph Smith Papers (2017-2020). Before her missions, Brenda served as the CFO for DigiCert, Inc. (2006-2012) and as the controller then Board officer for StorageCraft Technologies, Inc. (2005-2016). She has a long history of working with non-profit organizations, including BYU Religious Studies Department (2014-2018), FIRST Utah Robotics (2016-2020), and Utah Arts Festival (1996-2006). Brenda\'s love for genealogy has taken her researching throughout the world and she is excited to apply her skills to the Wilford Woodruff Papers project."},
		{"name": "Richard Lundquist", "title": "CFO", "image": "https://wp.wilfordwoodruffpapers.org/wp-content/uploads/2021/01/Rich-Lundquist.jpg", "bio": "Rich is the owner of Lundquist Ventures, LLC and currently serves as Regional Agent for the Murphy Business & Financial Corporation. His past business experience includes CFO for Silverline Finishing Inc., Hampton\'s Superior Dry Cleaning, and TimeShareWare, and Principal of Array Financial Services, LLC. He also served as the Board Chair and Treasurer of the Special Olympics of Utah. Rich completed both his undergraduate studies in Accounting and Business Management and his Masters of Accountancy with the Marriott School of Management at Brigham Young University."}
	],
	"Officers": [
		{"name": "J. Gregory Lake", "title": "President", "image": "https://wp.wilfordwoodruffpapers.org/wp-content/uploads/2020/05/Gregory-Lake-image-1.jpg", "bio": "Greg graduated from Brigham Young University with a BA in Economics after serving a full-time mission for The Church of Jesus Christ of Latter-Day Saints in Sweden. He then received his Juris Doctorate from the University of Arizona and has been in the private practice of law since 1987. He is currently working, with others, on a glossary of nineteenth century legal terms for the Joseph Smith Papers. Greg committed to leadership of the Wilford Woodruff Papers Foundation in order to continue to bring light to the Restoration."},
		{"name": "Jason R. Kotter", "title": "Vice-President", "image": "https://wp.wilfordwoodruffpapers.org/wp-content/uploads/2020/05/Jason-Kotter-image.jpg", "bio": "Jason attended Boise State University after serving a full-time mission for The Church of Jesus Christ of Latter-Day Saints in Canada. Having worked in the real estate industry most of his life, Jason co-founded Athlos Academies in 2006. Athlos focuses on providing schools with solutions centered around developing the whole child. In 2018 Jason initiated the idea of building a life-sized replica of the Tabernacle of Moses in Meridian Idaho as a catalyst for teaching the youth in his Stake about the temple. The Tabernacle has since been erected at various locations and reached thousands of individuals. He firmly believes that the Wilford Woodruff Papers will bring further clarity and understanding to the Gospel of Jesus Christ and enhance our appreciation of temple worship."},
		{"name": "Kristy Wheelwright Taylor", "title": "Secretary", "image": "https://wp.wilfordwoodruffpapers.org/wp-content/uploads/2020/05/Kristy-Taylors-headshot-1.jpg", "bio": "Kristy has a master\'s degree in Humanities from Brigham Young University and has since been an English Instructor at Purdue University, a copy editor, technical writer, caterer, travel writer, and historical researcher and writer. She is now a volunteer coordinator and a writer for various websites and publications. Her most recent project was a series of twelve articles on the life of Queen Elizabeth II for a digital and print magazine. Kristy is eager to learn more about Church History and to make Wilford Woodruff valuable documents available to a wider audience of readers and learners."}
	],
	"Advisors": [
		{"name": "Richard E. Turley, Jr.", "title": "Chair", "image": "https://wp.wilfordwoodruffpapers.org/wp-content/uploads/2020/05/Richard-E-Turley-Jr-image.jpg", "bio": "Rick recently retired from his position as Managing Director of the Church Communication Department of The Church of Jesus Christ of Latter-day Saints (2019-2020). Prior to Church Communication, he served as Managing Director of the Public Affairs Department (2016-2019), Assistant Church Historian and Recorder (2008-2016), Managing Director of the Family and Church History Department (2000-2008), Managing Director of the Family History Department (1996-2000), and Managing Director of the Church Historical Department (1986-2000). He was a member of the editorial board for the Joseph Smith Papers, the Board of the Brigham Young Center Foundation, and a general editor of the Journals of George Q. Cannon. Among his numerous publications, he coedited the second volume in the Revelations and Translations series of The Joseph Smith Papers (2011)."},
		{"name": "M. McClain Bybee", "title": "", "image": "https://wp.wilfordwoodruffpapers.org/wp-content/uploads/2020/05/McClain-Bybees-Image-1.jpg", "bio": "McClain is the retired Managing Director of the Philanthropies Department (formerly LDS Philanthropies) of the Office of the Presiding Bishopric. During his 39-year career he assisted donors in funding Church History projects, Family History projects, Church schools, Humanitarian projects, temples, and the Perpetual Education Fund, among others. McClain has been an ardent student of the Restoration of the Gospel of Jesus Christ during his entire adult life. Currently serving as a sealer in the Provo Temple, he continues to research and study the development of temple doctrine much of which was influenced by Wilford Woodruff. McClain believes the Wilford Woodruff Papers will eventually allow historians, researchers, and members of the Church to more fully appreciate the overarching importance of temple ordinances and covenants in the Plan of Salvation. "},
		{"name": "LaJean Purcell Carruth", "title": "", "image": "https://wp.wilfordwoodruffpapers.org/wp-content/uploads/2020/05/LaJean-P-Carruth-image-2.jpg", "bio": "LaJean works as a historian/writer for the Church History Department transcribing 19th and early 20th century documents written in Pitman shorthand, Taylor shorthand, and the Deseret Alphabet. She has transcribed sermons delivered by Brigham Young, John Taylor, and Wilford Woodruff, among others; the shorthand notes from the trials of those accused of killing Joseph Smith, and John D. Lee\'s trial following the Mountain Meadows Massacre; journals (including shorthand in Wilford Woodruff\'s journals); letters, and other historical documents. She has shown how the words in the Journal of Discourses differ significantly from the original shorthand record. She holds a Bachelor\'s and two Master\'s degrees from BYU, and a PhD from the University of Utah. She has an appreciation for Wilford\'s unique position as a chronicler of history and is thankful to be a part of this project to make his records more accessible."},
		{"name": "Matthew C. Godfrey", "title": "", "image": "https://wp.wilfordwoodruffpapers.org/wp-content/uploads/2020/07/Matt-Godfrey-1536x1024.jpg", "bio": "Matthew is a general editor and the managing historian of the Joseph Smith Papers. He is also a member of the Church History Department Editorial Board. Matthew holds a PhD in American and public history from Washington State University. Before joining the project, he was president of Historical Research Associates, a historical and archeological consulting firm headquartered in Missoula, Montana. He is the author of Religion, Politics, and Sugar: The Mormon Church, the Federal Government, and the Utah-Idaho Sugar Company, 1907–1921 (2007), and the coeditor of The Earth Shall Appear as the Garden of Eden: Essays in Mormon Environmental History (2018). He has also published numerous articles and various collections of essays. Because of Wilford Woodruff\'s involvement in virtually every important aspect of Latter-day Saint history in the nineteenth century, Matthew believes the publication of his papers to be a significant scholarly endeavor that will increase understanding of both the man and the church he eventually led."},
		{"name": "Andrew H. Hedges", "title": "", "image": "https://wp.wilfordwoodruffpapers.org/wp-content/uploads/2020/05/andrew_hedges.jpg", "bio": "Andy is a professor and Associate Chair of the Department of Church History and Doctrine at BYU. He received a PhD in American history from the University of Illinois at Urbana–Champaign, an MA in Near East studies from Brigham Young University, and a BS in Zoology from Weber State College. He was the lead editor of volumes 2 and 3 in the Journals series of The Joseph Smith Papers and served as Managing Historian of the project from 2012 to 2013. He has published on a variety of topics in early church history, with an emphasis on the Nauvoo and early Utah periods. He is currently serving as a member of the Executive Council of the Brigham Young Center Foundation."},
		{"name": "Stephen Woodruff Owen", "title": "", "image": "https://wp.wilfordwoodruffpapers.org/wp-content/uploads/2020/05/Stephen-W-Owen-Headshot.jpg", "bio": "Steve is a great-great grandson of Wilford Woodruff. He graduated in finance from the University of Utah after serving in the Texas San Antonio Mission. For the past 30 years he has owned and operated several Great Harvest Bread franchises in Utah and Nevada. Steve served as Young Men General President for the Church and on the National Executive Board of the Boy Scouts of America from 2015-2020. During that time he helped he Church transition from Scouting and develop the new Children and Youth program. Steve hopes the Wilford Woodruff Papers project will bring greater doctrinal understanding through making Wilford\'s many writings and journal entries accessible."},
		{"name": "R. Eric Smith", "title": "", "image": "https://wp.wilfordwoodruffpapers.org/wp-content/uploads/2020/07/R-Eric-Smith_crop-scaled-e1597238586102-1344x1536.jpg", "bio": "Eric is a general editor of the Joseph Smith Papers Project, the editorial manager of the Publications Division of the Church History Department of The Church of Jesus Christ of Latter-day Saints, and a member of the Church History Department Editorial Board. He received a BA in English from Brigham Young University and a JD from the University of Utah and practiced law in Salt Lake City before becoming at editor for the Curriculum Department of the Church. With Matthew J. Grow, Eric coedited The Council of Fifty: What the Records Reveal about Mormon History (2017).  He is grateful tor the opportunity to lend his documentary editing expertise to the Wilford Woodruff Papers project."},
		{"name": "Mark B. Woodruff", "title": "", "image": "https://wp.wilfordwoodruffpapers.org/wp-content/uploads/2021/01/Mark-B-Woodruff-1233x1536.jpg", "bio": "Mark serves as Executive Secretary to President Russell M. Nelson, President of the Provo Utah Oak Hills Stake, and as a sealer in the Provo Temple. His previous positions include Assistant to the Commissioner and Secretary to the Church Board of Education, Director of Missionary Services for the Missionary Department, and Director of the BYU Public Affairs Office. He earned both his PhD and MBA degrees from Brigham Young University. Mark also served as mission president of the Brazil Recife Mission with his wife Peggy Petersen Woodruff. He is a descendant of Wilford Woodruff and a past president of the Wilford Woodruff Family Association."},
		{"name": "Steven C. Wheelwright", "title": "", "image": "/files/asset/bio/s-c-wheelwright.jpg", "bio": "After graduating from the University of Utah, Steve Wheelwright received an MBA and a PhD from The Stanford University Graduate School of Business. During his academic career, Steve taught at INSEAD, a private business school in Fontainebleau, France, the Stanford Graduate School of Business where he also served as the Chair of the Strategic Management Dept., and the Harvard Business School where he also served as a Senior Associate Dean overseeing the MBA program, then overseeing Faculty Planning and Development, and concluding as Chairman of HBS Publishing. Since his retirement from Harvard, he and his wife, Margaret Steele Wheelwright, presided over the England London Mission, served one year at BYU-Idaho, presided over BYU-Hawaii for 8 years, and presided over the Boston Temple, where they became deeply interested in Wilford Woodruff\'s contributions to the temple ordinances after reading Jennifer Mackley\'s book, Wilford Woodruff\'s Witness: The Development of Temple Doctrine. They are grateful for the blessing it is to have access to Wilford Woodruff\'s writings on this topic and want to assist this effort so everyone can learn from his documents and revelations. Steve and Margaret have 5 children, 20 grandchildren, and 2 great-grandchildren, with more on the way. They live in Oakley, Utah."}
	]}',true);
    }
}
