@unlessrole('Editor')
<script
    src="https://app.wonderchat.io/scripts/wonderchat.js"
    data-name="wonderchat"
    data-address="app.wonderchat.io"
    data-id="clxz3i0pe05z9m9h6qett0qvp"
    data-widget-size="large"
    data-widget-button-size="extraLarge"
    defer
></script>
@endunlessrole
